POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZvbGxhbnRyZSIsImlkIjoiNWRiNzRiM2YyMzE1YzAxNmIzNjY5ODNhIiwiaWF0IjoxNTcyMzEwNTk3fQ.ZQhjfkepVIJxEd9LW743jbKugisypmqS3-8U84YnZNM

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
    "likes": 10
}